export default [
  {name: 'mTechVille', point: 5},

  {name: 'Helsinki', point: 6},
  {name: 'Tukholma', point: 3},
  {name: 'Oslo', point: 2},
  {name: 'Tokio', point: 2},
  {name: 'Peking', point: 2},
  {name: 'Lontoo', point: 3},
  {name: 'Pariisi', point: 2},
  {name: 'Moskova', point: 3},
  {name: 'Kairo', point: 3},
  {name: 'Amsterdam', point: 6},
  {name: 'Madrid', point: 3},
  {name: 'Rooma', point: 3},
  {name: 'Ateena', point: 1},
  {name: 'Istanbul', point: 5},
  {name: 'Baghdad', point: 4},
  {name: 'Teheran', point: 4},
  {name: 'Kalkutta', point: 3},
  {name: 'Bangkok', point: 4},
  {name: 'Jakarta', point: 5},
  {name: 'Shanghai', point: 5},
  {name: 'Xi\'an', point: 3},
  {name: 'Kyoto', point: 3},
  {name: 'Manila', point: 2},
  {name: 'Ulaanbatar', point: 5},
  {name: 'Ouagadougou', point: 5},
  {name: 'Lagos', point: 2},
  {name: 'Brasilia', point: 5},
  {name: 'Chicago', point: 3},
  {name: 'Atlanta', point: 5},
  {name: 'Dallas', point: 3},
  {name: 'Sydney', point: 3},
  {name: 'Miami', point: 3},
  {name: 'Dubai', point: 2},
  {name: 'Delhi', point: 2},
  {name: 'Auckland', point: 4},
  {name: 'Singapore', point: 5},

  {name: 'Los Angeles', point: 6, full: 4},
  {name: 'Las Vegas', point: 6, full: 4},
  {name: 'San Fransisco', point: 8, full: 4},
  {name: 'New York', point: 5, full: 4},
  {name: 'New Orleans', point: 6, full: 4},
  {name: 'Hong Kong', point: 6, full: 5},
  {name: 'Buenos Aires', point: 9, full: 7},
  {name: 'Rio de Janeiro', point: 9, full: 7},
  {name: 'Addis Abaha', point: 7, full: 6},
  {name: 'Cape Town', point: 7, full: 5},
  {name: 'Mexico City', point: 6, full: 6},

  {name: 'Minas Tirith', point: 8, full: 6},
  {name: 'Minas Morgul', point: 9, full: 6},

  {name: 'Agrabah', point: 2},
  {name: 'Megacity', point: 4},
  {name: 'Atlantis', point: 5},
  {name: 'Baldur', point: 3},
  {name: 'Tylypahka', point: 4}
  
]