export default [
  {name: 'mTechVille', point: 5},

  {name: 'Helsinki', point: 6},
  {name: 'Turku', point: 3},
  {name: 'Tampere', point: 3},
  {name: 'Oulu', point: 2},
  {name: 'Rovaniemi', point: 4},
  {name: 'Jyväskylä', point: 5},
  {name: 'Pori', point: 2},
  {name: 'Kotka', point: 3},
  {name: 'Espoo', point: 2},
  {name: 'Vantaa', point: 3},
  {name: 'Seinäjoki', point: 5},
  {name: 'Joensuu', point: 4},
  {name: 'Lappeenranta', point: 7},
  {name: 'Savonlinna', point: 5},
  {name: 'Pietarsaari', point: 6},
  {name: 'Utsjoki', point: 3},
  {name: 'Kilpisjärvi', point: 6},
  {name: 'Lahti', point: 3},
  {name: 'Mikkeli', point: 3},
  {name: 'Vaasa', point: 3},
  {name: 'Maarienhamina', point: 7},

  {name: 'Tukholma', point: 3},
  {name: 'Oslo', point: 2},
  {name: 'Kööpenhamina', point: 6},
  {name: 'Tallinna', point: 3},
  {name: 'Riika', point: 3},
  {name: 'Vilna', point: 3},
  {name: 'Lontoo', point: 3},
  {name: 'Pariisi', point: 2},
  {name: 'Moskova', point: 3},
  {name: 'Praha', point: 3},
  {name: 'Vienna', point: 4},
  {name: 'Berliini', point: 3},
  {name: 'Varsova', point: 3},
  {name: 'Minsk', point: 3},
  {name: 'Hampuri', point: 3},
  {name: 'Lissabon', point: 5},
  {name: 'Napoli', point: 2},
  {name: 'Amsterdam', point: 6},
  {name: 'Madrid', point: 3},
  {name: 'Rooma', point: 3},
  {name: 'Ateena', point: 1},
  {name: 'Pietari', point: 3},
  {name: 'Venetsia', point: 5},
  {name: 'Milano', point: 4},
  {name: 'Budapest', point: 4},
  {name: 'Bucharest', point: 5},
  {name: 'Manchester', point: 3},
  {name: 'Liverpool', point: 5},
  {name: 'Dublin', point: 3},
  {name: 'Barcelona', point: 5},
  {name: 'Brysseli', point: 4},
  {name: 'Reykjavik', point: 4},
  {name: 'Munchen', point: 3},
  {name: 'Frankfurt', point: 5},
  {name: 'Lyon', point: 2},
  {name: 'Marseille', point: 3},
  {name: 'Kiova', point: 3},

  {name: 'Kairo', point: 3},
  {name: 'Istanbul', point: 5},
  {name: 'Baghdad', point: 4},
  {name: 'Teheran', point: 4},
  {name: 'Kalkutta', point: 3},
  {name: 'Bangkok', point: 4},
  {name: 'Jakarta', point: 5},
  {name: 'Shanghai', point: 5},
  {name: 'Xi\'an', point: 3},
  {name: 'Kyoto', point: 3},
  {name: 'Manila', point: 2},
  {name: 'Ulaanbatar', point: 5},
  {name: 'Ouagadougou', point: 5},
  {name: 'Lagos', point: 2},
  {name: 'Brasilia', point: 5},
  {name: 'Chicago', point: 3},
  {name: 'Atlanta', point: 5},
  {name: 'Dallas', point: 3},
  {name: 'Sydney', point: 3},
  {name: 'Miami', point: 3},
  {name: 'Dubai', point: 2},
  {name: 'Delhi', point: 2},
  {name: 'Auckland', point: 4},
  {name: 'Singapore', point: 5},
  {name: 'Vladivostok', point: 5},
  {name: 'Seoul', point: 3},
  {name: 'Pyongjang', point: 5},
  {name: 'Irkutsk', point: 2},
  {name: 'Ankara', point: 2},
  {name: 'Tokio', point: 2},
  {name: 'Peking', point: 2},

  {name: 'Los Angeles', point: 6, full: 4},
  {name: 'Las Vegas', point: 6, full: 4},
  {name: 'San Fransisco', point: 8, full: 4},
  {name: 'New York', point: 5, full: 4},
  {name: 'New Orleans', point: 6, full: 4},
  {name: 'Hong Kong', point: 6, full: 5},
  {name: 'Buenos Aires', point: 9, full: 7},
  {name: 'Rio de Janeiro', point: 9, full: 7},
  {name: 'Addis Abaha', point: 7, full: 6},
  {name: 'Cape Town', point: 7, full: 5},
  {name: 'Mexico City', point: 6, full: 6},

  {name: 'Minas Tirith', point: 8, full: 6},
  {name: 'Minas Morgul', point: 9, full: 6},
  {name: 'South Park', point: 8, full: 6},
  {name: 'Shangri-la', point: 8, full: 7},
  {name: 'El Dorado', point: 3, full: 3},

  {name: 'Agrabah', point: 2},
  {name: 'Megacity', point: 4},
  {name: 'Atlantis', point: 5},
  {name: 'Baldur', point: 3},
  {name: 'Gotham', point: 3},
  {name: 'Springfield', point: 6},
  {name: 'Avalon', point: 3},
  {name: 'Tylypahka', point: 4}
  
]